#-------------CLEO IMGUI MOBILE---------

# Order of "CLEO ImGui"

0F01=4,imgui_begin %1d% show %2d% flags %3d% mouse_visible %4d% 
0F02=0,imgui_end 
0F03=3,imgui_checkbox label %1d% imguitypeflags %2d% var (int) %3d% 
0F04=3,imgui_button label %1d% width (float) %2d% height (float) %3d% 
0F05=5,imgui_calc_text_height text %1d% hide_after (bool) %2d% warp_width (float) %3d% imguitypeflags %4d% pointer/var (float) %5d% 
0F06=5,imgui_calc_text_width text %1d% hide_after (bool) %2d% warp_width (float) %3d% imguitypeflags %4d% pointer/var (float) %5d% 
0F07=3,imgui_set_next_window_pos pos x (float) %1d% pos y (float) %2d% imguicond %3d% 
0F08=3,imgui_set_window_pos pos x (float) %1d% pos y (float) %2d% imguicond %3d% 
0F09=1,imgui_get_font_size var (float) %1d% 
0F0A=3,imgui_set_next_window_size width (float) %1d% height (float) %2d% imguicond %3d% 
0F0B=3,imgui_set_window_size width (float) %1d% height (float) %2d% imguicond %3d% 
0F0C=0,imgui_show_demo_window 
0F0D=0,imgui_show_style_editor 
0F0E=1,imgui_text text %1d% 
0F0F=1,imgui_text_wrapped text %1d% 
0F10=1,imgui_text_disabled text %1d% 
0F11=5,imgui_text_colored text %1d% red (float) %2d% green (float) %3d% blue (float) %4d% alpha (float) %5d% 
0F12=2,imgui_columns count (int) %1d% border (int) %2d% 
0F13=0,imgui_next_column 
0F14=0,imgui_spacing 
0F15=2,imgui_dummy padding x (float) %1d% padding y (float) %2d% 
0F16=0,imgui_sameline 
0F17=7,imgui_slider_int label %1d% imguitypeflags %2d% var %3d% min (int) %4d% max (int) %5d% imguisliderflags %6d% imguislidercount %7d% 
0F18=7,imgui_slider_float label %1d% imguitypeflags %2d% var %3d% min (float) %4d% max (float) %5d% imguisliderflags %6d% imguislidercount %7d% 
0F19=5,imgui_color_edit label %1d% imguitypeflags %2d% var %3d% imguicoloreditflags %4d% imguicoloreditalpha %5d% 
0F1A=5,imgui_color_picker label %1d% imguitypeflags %2d% var %3d% imguicoloreditflags %4d% imguicoloreditalpha %5d% 
0F1B=5,imgui_begin_child label %1d% width (float) %2d% height (float) %3d% border (int) %4d% imguiwindowflags %5d% 
0F1C=0,imgui_end_child 
0F1D=5,imgui_input_int label %1d% imguitypeflags %2d% var %3d% imguiinputtextflags %4d% imguiinputcount %5d% 
0F1E=5,imgui_input_float label %1d% imguitypeflags %2d% var %3d% imguiinputtextflags %4d% imguiinputcount %5d% 
0F1F=5,imgui_input_text label %1d% hint %2d% var (char) %3d% buffer size (int) %4d% imguiinputtextflags %5d% 
0F20=6,imgui_input_text_multiline label %1d% var (char) %2d% buffer size (int) %3d% width (float) %4d% height (float) %5d% imguiinputtextflags %6d% 
0F25=0,imgui_separator 
0F26=1,imgui_get_cleo_imgui_version var (float) %1d% 
0F27=1,imgui_get_version var (float) %1d% 
0F28=1,imgui_get_framerate var (int) %1d% 
0F29=8,imgui_color_button label %1d% red (float) %2d% green (float) %3d% blue (float) %4d% alpha (float) %5d% imguicoloreditflags %6d% width (float) %7d% height (float) %8d% 
0F2A=0,imgui_bullet 
0F2B=1,imgui_bullet_text label %1d% 
0F2C=0,imgui_newline 
0F2D=1,imgui_set_tooltip label %1d% 
0F2E=6,imgui_color_tooltip label %1d% red (float) %2d% green (float) %3d% blue (float) %4d% alpha (float) %5d% imguicoloreditflags %6d% 
0F2F=2,imgui_is_item_hovered indentifier %1d% imguihoveredflags %2d% 
0F30=1,imgui_is_item_focused indentifier %1d% 
0F31=1,imgui_is_item_activated indentifier %1d% 
0F32=1,imgui_is_item_deactivated indentifier %1d% 
0F33=1,imgui_is_item_active indentifier %1d% 
0F34=2,imgui_is_item_clicked indentifier %1d% imguimousebutton %2d% 
0F35=2,imgui_is_window_hovered indentifier %1d% imguihoveredflags %2d% 
0F36=2,imgui_is_window_focused indentifier %1d% imguihoveredflags %2d% 
0F37=4,imgui_radio_button label %1d% imguitypeflags %2d% pointer/var (int) %3d% number (int) %4d% 
0F38=2,imgui_collasping_header label %1d% imguitreenodeflags %2d% 
0F39=4,imgui_progress_bar label %1d% fraction (float) %2d% width (float) %3d% height (float) %4d% 
0F3A=2,imgui_get_window_posy imguitypeflags %1d% pointer/var (float) %2d% 
0F3B=2,imgui_get_window_posx imguitypeflags %1d% pointer/var (float) %2d% 
0F3C=2,imgui_get_window_width imguitypeflags %1d% pointer/var (float) %2d% 
0F3D=2,imgui_get_window_height imguitypeflags %1d% pointer/var (float) %2d% 
0F3E=5,imgui_selectable label %1d% check mark (int) %2d% imguiselectableflags %3d% width (float) %4d% height (float) %5d% 
0F40=2,imgui_load_image path %1d% var (int) %2d% 
0F41=4,imgui_image indentifier %1d% var (int) %2d% width (float) %3d% height (float) %4d% 
0F42=16,imgui_image_ex indentifier %1d% var (int) %2d% width (float) %3d% height (float) %4d% uv x (float) %5d% uv0 y (float) %6d% uv x (float) %7d% uv0 y (float) %8d% red (float) %9d% green (float) %10d% blue (float) %11d% alpha (float) %12d% border red (float) %13d% border green (float) %14d% border blue (float) %15d% border alpha (float) %16d% 
0F43=4,imgui_image_button indentifier %1d% var (int) %2d% width (float) %3d% height (float) %4d% 
0F44=16,imgui_image_button_ex indentifier %1d% var (int) %2d% width (float) %3d% height (float) %4d% uv0 x (float) %5d% uv0 y (float) %6d% uv1 x (float) %7d% uv1 y (float) %8d% red (float) %9d% green (float) %10d% blue (float) %11d% alpha (float) %12d% border red (float) %13d% border green (float) %14d% border blue (float) %15d% border alpha (float) %16d% 
#0F45=1,imgui_get_game_path pointer (char) %1d% 
0F46=4,imgui_invisible_button label %1d% width (float) %2d% height (float) %3d% imguibuttonflags %4d% 
0F47=6,imgui_drawlist_add_circle center x (float) %1d% center y (float) %2d% radius (float) %3d% color (int) %4d% segment (int) %5d% thickness (int) %6d% 
0F48=5,imgui_drawlist_add_circle_filled center x (float) %1d% center y (float) %2d% radius (float) %3d% color (int) %4d% segment (int) %5d% 
0F49=8,imgui_drawlist_add_rect min x (float) %1d% min y (float) %2d% max x (float) %3d% max y (float) %4d% color (int) %5d% rounding (int) %6d% corners (int) %7d% thickness (int) %8d% 
0F4A=7,imgui_drawlist_add_rect_filled min x (float) %1d% min y (float) %2d% max x (float) %3d% max y (float) %4d% color (int) %5d% rounding (int) %6d% corners (int) %7d% 
0F4B=8,imgui_drawlist_add_rect_filled_multicolor min x (float) %1d% min y (float) %2d% max x (float) %3d% max y (float) %4d% color up left (int) %5d% color up right (int) %6d% color down left (int) %7d% color down right (int) %8d% 
0F4C=5,imgui_drawlist_add_text text %1d% pos x (float) %2d% pos y (float) %3d% radius (float) %4d% color (int) %5d% 
0F4D=8,imgui_drawlist_add_triangle point1 x (float) %1d% point1 y (float) %2d% point2 x (float) %3d% point2 y (float) %4d% point3 x (float) %5d% point3 y (float) %6d% color (int) %7d% thickness (int) %8d% 
0F4E=7,imgui_drawlist_add_triangle_filled point1 x (float) %1d% point1 y (float) %2d% point2 x (float) %3d% point2 y (float) %4d% point3 x (float) %5d% point3 y (float) %6d% color (int) %7d% 
0F4F=0,imgui_begin_main_menu_bar 
0F50=0,imgui_end_main_menu_bar 
0F51=1,imgui_menu_item label %1d% 
0F52=0,imgui_style_colors_classic 
0F53=0,imgui_style_colors_dark 
0F54=0,imgui_style_colors_default 
0F55=0,imgui_style_colors_light 
0F57=2,imgui_get_style imguistyleoffsets %1d% var (float) %2d% 
0F58=2,imgui_set_style imguistyleoffsets %1d% value (float) %2d% 
0F59=2,imgui_set_style_int imguistyleoffsets %1d% value (int) %2d% 
0F5A=5,imgui_get_color imguicoloroffsets %1d% red (float) %2d% green (float) %3d% blue (float) %4d% alpha (float) %5d% 
0F5B=5,imgui_set_color imguicoloroffsets %1d% red (float) %2d% green (float) %3d% blue (float) %4d% alpha (float) %5d% 
0F5C=1,imgui_push_item_width width (float) %1d% 
0F5D=0,imgui_pop_item_width 
0F5E=2,imgui_push_item_flag imguiitemflags %1d% enabled (int) %2d% 
0F5F=0,imgui_pop_item_flag 
0F60=2,imgui_get_window_content_region_width imguitypeflags %1d% pointer/var (float) %2d% 
0F61=2,imgui_get_frame_height imguitypeflags %1d% pointer/var (float) %2d% 
0F62=1,imgui_get_frame_height_with_spacing var (float) %1d% 
0F63=2,imgui_get_style_int imguistyleoffsets %1d% var (int) %2d% 

# Order of "CLEO ImGui Redux"

#2200 IMGUI_BEGIN_FRAME
#2201 IMGUI_END_FRAME
2202=7,%7d% = imgui_begin %1d% state %2d% no_title %3d% no_resize %4d% no_move %5d% auto_resize %6d%
2203=0,imgui_end // is 0F02
2204=1,imgui_begin_main_menu_bar %1d% state %2d%
2205=0,imgui_end_main_menu_bar // is 0F50
2206=1,imgui_begin_child %1d%
2207=0,imgui_end_child // is 0F1C
2208=3,%3d% = imgui_tabs %1d% name %2d% tabNames
2209=2,imgui_collasping_header %1d% flags %2d%  // is 0F38
220A=3,imgui_set_window_pos %1d% %2d% cond %3d% // is 0F08
220B=3,imgui_set_window_size %1d% %2d% cond %3d% // is 0F0B
220C=3,imgui_set_next_window_pos %1d% %2d% cond %3d% // is 0F07
220D=3,imgui_set_next_window_size %1d% %2d% cond %3d% // is 0F0A
220E=1,imgui_text %1d% // is 0F0E
220F=1,imgui_text_centered %1d% text
2210=1,imgui_text_disabled %1d% // is 0F10
2211=1,imgui_text_wrapped %1d% // is 0F0F
2212=5,imgui_text_colored %1d% rgba_float %2d% %3d% %4d% %5d%  // is 0F11
2213=1,imgui_bullet_text %1d% // is 0F2B
2214=0,imgui_bullet // is 0F2A
2215=3,%3d% = imgui_checkbox %1d% flags %2d% // is 0F03
2216=4,%4d% = imgui_combo %1d% name %2d% options %3d% init_selection
2217=1,imgui_set_tooltip %1d% // is 0F2D
2218=3,imgui_button %1d% scale %2d% %3d% // is 0F04
2219=4,imgui_image_button %1d% imagen %2d% scale %3d% %4d% // is 0f43
221A=3,imgui_invisible_button %1d% scale %2d% %3d% 
221B=7,imgui_color_button %1d% rgba_float %2d% %3d% %4d% %5d% scale %6d% %7d%
221C=2,%2d% = imgui_arrow_button %1d% name %2d% dir
221D=5,%5d% = imgui_slider_int %1d% init %2d% min %3d% max %4d% // init, not working 
221E=5,%5d% = imgui_slider_float %1d% init %2d% min %3d% max %4d% // init, not working 
221F=5,%5d% = imgui_input_int %1d% init %2d% min %3d% max %4d% // init, min, max, not working
2220=5,%5d% = imgui_input_float %1d% init %2d% min %3d% max %4d% // init, min, max, not working
2221=2,%2d% = imgui_input_text %1d%
2222=4,%4d% = imgui_radio_button %1d% selected %2d% number %3d% // selected, not working 
2223=5,imgui_color_picker %1d% rgba_int %2d% %3d% %4d% %5d%
2224=4,%4d% = imgui_menu_item %1d% selected %2d% enabled %3d%
2225=3,%3d% = imgui_selectable %1d% selected %2d%
2226=2,imgui_dummy_padding %1d% %2d% // is 0F15
2227=0,imgui_sameline // is 0F16
2228=0,imgui_newline // is 0F2C
2229=1,imgui_columns %1d% 
222A=0,imgui_next_column // is 0F13
222B=0,imgui_spacing // is 0F14
222C=0,imgui_separator // is 0F25
222D=1,imgui_push_item_width %1d% // is 0F5C
222E=0,imgui_pop_item_width // is 0F5D
222F=2,%2d% = imgui_is_item_active %1d% id // id, not working 
2230=2,%2d% = imgui_is_item_clicked %1d% id // id, not working
2231=2,%2d% = imgui_is_item_focused %1d% id // id, not working
2232=2,%2d% = imgui_is_item_hovered %1d% id // id, not working
2233=2,imgui_set_item_int %1d% id %2d% val // it does nothing
2234=2,imgui_set_item_float %1d% id %2d% val // it does nothing
2235=2,imgui_set_item_text %1d% id %2d% val // it does nothing
2236=4,imgui_set_image_bg_color %1d% %2d% %3d% %4d% rgba_float
2237=4,imgui_set_image_tint_color %1d% %2d% %3d% %4d% rgba_float
2238=2,%2d% = imgui_load_image %1d% path // is 0F40 & it does nothing
2239=1,imgui_free_image %1d%
223A=2,imgui_push_style_var %1d% styleVar %2d% val
223B=3,imgui_push_style_var2 %1d% styleVar %2d% x %3d% y
223C=5,imgui_push_style_color %1d% col %2d% r %3d% g %4d% b %5d% a
223D=1,imgui_pop_style_var %1d% count
223E=1,imgui_pop_style_color %1d% count
223F=1,%1d% = imgui_get_foreground_drawlist
2240=1,%1d% = imgui_get_background_drawlist
2241=1,%1d% = imgui_get_window_drawlist
2242=8,imgui_drawlist_add_text %8d% at %2d% %3d% rgba_int %4d% %5d% %6d% %7d% layer %1d%
2243=10,imgui_drawlist_add_line %1d% drawList %2d% xy_begin %3d% %4d% xy_end %5d% %6d% rgba_int %7d% %8d% %9d% %10d% thickness
2244=1,%1d% = imgui_get_framerate // is 0F28
2246=1,%1d% = imgui_get_cleo_imgui_version // is 0F27
2245=1,%1d% = imgui_get_version // is 0F26
2247=1,imgui_set_cursor_visible %1d% show
2248=1,%1d% = imgui_get_frame_height // is 0F61
2249=3,imgui_get_window_pos flag %1d% xy %2d% %3d% 
224A=3,imgui_get_window_size %1d% uniqueId %2d% width %3d% height
224B=3,imgui_calc_text_size %1d% text %2d% width %3d% height
224C=2,%2d% = imgui_get_window_content_region_width %1d% // is 0F60
224D=5,imgui_get_scaling_size %1d% uniqueId %2d% count %3d% spacing %4d% x %5d% y
224E=2,imgui_get_display_size %1d% width %2d% height
224F=1,imgui_set_next_window_transparency %1d% alpha
2250=1,imgui_set_message %1d% text

# AML Exclusives

2300=1,imgui_keyboard_text_leght %1d% // for imgui_input_text & imgui_keyboard_show
2301=2,imgui_keyboard_show %1d% var %2d%
2302=0,imgui_keyboard_hide
2303=0,imgui_keyboard_is_visible
2304=0,imgui_image_reset_color
2305=1,imgui_keyboard_set_enter_mode %1d% // 1 = "\n" || 0 = close()

2310=1,imgui_indent %1d%
2311=1,imgui_unindent %1d%
2312=0,imgui_begin_group
2313=0,imgui_end_group
2314=0,imgui_align_text_to_frame_padding
2315=1,%1d% = imgui_get_text_line_height
2316=1,%1d% = imgui_get_text_line_height_with_spacing
2317=1,imgui_small_button %1d%
2318=3,imgui_checkbox_flags_int %1d% var %2d% flag_value %3d%
2319=2,imgui_radio_button_active %1d% active %2d%
231A=6,imgui_input_int_x %1d% count %2d% var0 %3d% var1 %4d% var2 %5d% var3 %6d%
231B=6,imgui_input_float_x %1d% count %2d% var0 %3d% var1 %4d% var2 %5d% var3 %6d%
231C=5,imgui_drag_int %1d% var %2d% speed %3d% min %4d% max %5d%
231D=9,imgui_drag_int_x %1d% count %2d% speed %3d% min %4d% max %5d% var0 %6d% var1 %7d% var2 %8d% var3 %9d%
231E=5,imgui_drag_float %1d% var %2d% speed %3d% min %4d% max %5d%
231F=9,imgui_drag_float_x %1d% count %2d% speed %3d% min %4d% max %5d% var0 %6d% var1 %7d% var2 %8d% var3 %9d%
2320=8,imgui_slider_int_x %1d% count %2d% min %3d% max %4d% var0 %5d% var1 %6d% var2 %7d% var3 %8d%
2321=8,imgui_slider_float_x %1d% count %2d% min %3d% max %4d% var0 %5d% var1 %6d% var2 %7d% var3 %8d%
2322=4,imgui_slider_angle %1d% var %2d% deg_min %3d% deg_max %4d%
2323=2,imgui_value_bool %1d% value %2d%
2324=2,imgui_value_int %1d% value %2d%
2325=2,imgui_value_float %1d% value %2d%

2326=1,imgui_tree_node %1d%
2327=2,imgui_tree_node_ex %1d% flags %2d%
2328=1,imgui_tree_push %1d%
2329=0,imgui_tree_pop
232A=3,imgui_collapsing_header_ex %1d% flags %2d% var_visible %3d%
232B=2,imgui_set_next_item_open %1d% cond %2d%

232C=2,imgui_open_popup %1d% flags %2d%
232D=2,imgui_begin_popup %1d% flags %2d%
232E=0,imgui_end_popup
232F=0,imgui_close_current_popup
2330=2,imgui_open_popup_on_item_click %1d% flags %2d%
2331=2,imgui_begin_popup_context_item %1d% flags %2d%
2332=2,imgui_begin_popup_context_window %1d% flags %2d%
2333=2,imgui_begin_popup_context_void %1d% flags %2d%
2334=2,imgui_is_popup_open %1d% flags %2d%

2335=2,imgui_begin_tab_bar %1d% flags %2d%
2336=0,imgui_end_tab_bar
2337=2,imgui_begin_tab_item %1d% flags %2d%
2338=0,imgui_end_tab_item
2339=2,imgui_tab_item_button %1d% flags %2d%
233A=1,imgui_set_tab_item_closed %1d%

233B=6,imgui_begin_table %1d% column %2d% flags %3d% outer_size_x %4d% outer_size_y %5d% inner_width %6d%
233C=0,imgui_end_table
233D=2,imgui_table_next_row %1d% min_row_height %2d%
233E=0,imgui_table_next_column
233F=1,imgui_table_set_column_index %1d%
2340=4,imgui_table_setup_column %1d% flags %2d% init_width %3d% user_id %4d%
2341=2,imgui_table_setup_scroll_freeze %1d% rows %2d%
2342=0,imgui_table_headers_row
2343=1,imgui_table_header %1d%
2344=1,%1d% = imgui_table_get_column_count
2345=1,%1d% = imgui_table_get_column_index
2346=1,%1d% = imgui_table_get_row_index
2347=1,%1d% = imgui_table_get_column_name %1d%
2348=1,%1d% = imgui_table_get_column_flags %1d%
2349=2,imgui_table_set_column_enabled %1d% enabled %2d%
234A=3,imgui_table_set_bg_color %1d% color %2d% column_n %3d%

234B=2,imgui_label_text %1d% text %2d%
234C=0,imgui_begin_tooltip
234D=0,imgui_end_tooltip
234E=2,imgui_begin_menu %1d% enabled %2d%
234F=0,imgui_end_menu
2350=4,imgui_menu_item_ex %1d% shortcut %2d% selected %3d% enabled %4d%
2352=3,imgui_begin_list_box %1d% width %2d% height %3d%
2353=0,imgui_end_list_box
2354=4,imgui_list_box %1d% items %2d% var %3d% height_items %4d%
2355=8,imgui_plot_lines %1d% values_addr %2d% count %3d% overlay %4d% scale_min %5d% scale_max %6d% graph_w %7d% graph_h %8d%
2356=8,imgui_plot_histogram %1d% values_addr %2d% count %3d% overlay %4d% scale_min %5d% scale_max %6d% graph_w %7d% graph_h %8d%
2357=1,%1d% = imgui_get_time
2358=1,%1d% = imgui_get_frame_count

2359=4,imgui_set_image_uv %1d% %2d% %3d% %4d%
235A=4,imgui_set_image_border_color %1d% %2d% %3d% %4d% rgba_float